--    {
--        'mrcjkb/rustaceanvim',
--        version = '^6', -- Recommended
--        lazy = false,
--        init = function()
--            -- Configure rustaceanvim here
--            vim.g.rustaceanvim = {
--                tools = {
--                    float_win_config = {
--                        border = "single",
--                    },
--                },
--                server = {
--                    on_attach = function(_, bufnr)
--                        vim.keymap.set("n", "<leader>cR", function()
--                            vim.cmd.RustLsp("codeAction")
--                        end, { desc = "Code Action", buffer = bufnr })
--                        vim.keymap.set("n", "<leader>dr", function()
--                            vim.cmd.RustLsp("debuggables")
--                        end, { desc = "Rust Debuggables", buffer = bufnr })
--                    end,
--
--                    settings = {
--                        ["rust-analyzer"] = {
--                            cargo = {
--                                allFeatures = true,
--                                loadOutDirsFromCheck = true,
--                                buildScripts = {
--                                    enable = true,
--                                },
--                            },
--                            -- Add clippy lints for Rust.
--                            checkOnSave = true,
--                            procMacro = {
--                                enable = true,
--                                ignored = {
--                                    -- ["async-trait"] = { "async_trait" },
--                                    ["napi-derive"] = { "napi" },
--                                    ["async-recursion"] = { "async_recursion" },
--                                },
--                            },
--                            -- We have to set watcher to client, otherwise it's 'Roots Scanned' loop (fseventd related)
--                            files = {
--                                watcher = 'client'
--                            }
--                        },
--                    },
--                    capabilities = {
--                        workspace = {
--                            didChangeConfiguration = {
--                                dynamicRegistration = true,
--                            },
--                        },
--                        textDocument = {
--                            completion = {
--                                completionItem = {
--                                    snippetSupport = false,
--                                },
--                            }
--                        },
--                    },
--                },
--            }
--        end
--    },
--    {
--        "nvim-neotest/neotest",
--        lazy = true,
--        cmd = "Neotest",
--        dependencies = {
--            "nvim-neotest/nvim-nio",
--            "nvim-lua/plenary.nvim",
--            "antoinemadec/FixCursorHold.nvim",
--            "nvim-treesitter/nvim-treesitter",
--            "nvim-neotest/neotest-go",
--        },
--        config = function()
--            require("neotest").setup({
--                adapters = {
--                    require('neotest-go')
--                },
--                quickfix = {
--                    open = false,
--                    enabled = false,
--                },
--                status = {
--                    enabled = true,
--                    signs = true, -- Sign after function signature
--                    virtual_text = false
--                },
--                icons = {
--                    child_indent = "│",
--                    child_prefix = "├",
--                    collapsed = "─",
--                    expanded = "╮",
--                    failed = "✘",
--                    final_child_indent = " ",
--                    final_child_prefix = "╰",
--                    non_collapsible = "─",
--                    passed = "✓",
--                    running = "",
--                    running_animated = { "/", "|", "\\", "-", "/", "|", "\\", "-" },
--                    skipped = "↓",
--                    unknown = ""
--                },
--                floating = {
--                    max_height = 0.9,
--                    max_width = 0.9,
--                    options = {}
--                },
--                summary = {
--                    open = "botright vsplit | vertical resize 60",
--                    mappings = {
--                        attach = "a",
--                        clear_marked = "M",
--                        clear_target = "T",
--                        debug = "d",
--                        debug_marked = "D",
--                        expand = { "<CR>", "<2-LeftMouse>" },
--                        expand_all = "e",
--                        jumpto = "i",
--                        mark = "m",
--                        next_failed = "J",
--                        output = "o",
--                        prev_failed = "K",
--                        run = "r",
--                        run_marked = "R",
--                        short = "O",
--                        stop = "u",
--                        target = "t",
--                        watch = "w"
--                    },
--                },
--                highlights = {
--                    adapter_name = "NeotestAdapterName",
--                    border = "NeotestBorder",
--                    dir = "NeotestDir",
--                    expand_marker = "NeotestExpandMarker",
--                    failed = "NeotestFailed",
--                    file = "NeotestFile",
--                    focused = "NeotestFocused",
--                    indent = "NeotestIndent",
--                    marked = "NeotestMarked",
--                    namespace = "NeotestNamespace",
--                    passed = "NeotestPassed",
--                    running = "NeotestRunning",
--                    select_win = "NeotestWinSelect",
--                    skipped = "NeotestSkipped",
--                    target = "NeotestTarget",
--                    test = "NeotestTest",
--                    unknown = "NeotestUnknown"
--                }
--            })
--        end
--    }
--}
--
