tap "charmbracelet/tap"
tap "github/gh", trusted: true
tap "hashicorp/tap", trusted: true
tap "helm/tap", trusted: true
tap "lihaoyun6/tap", trusted: true
tap "ory/tap", trusted: true
tap "osx-cross/arm", trusted: true
tap "osx-cross/avr", trusted: true
tap "qmk/qmk", trusted: true
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# General-purpose data compression with high compression ratio
brew "xz"
# Cryptographic algorithms and formats library in C++
brew "botan"
# Powerful, enterprise-ready, open source web server with automatic HTTPS
brew "caddy"
# Create and run Linux containers using lightweight virtual machines
brew "container"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Container Signing
brew "cosign"
# Tool for interacting with remote images and registries
brew "crane"
# USB programmer
brew "dfu-util"
# Tool for exploring each layer in a docker image
brew "dive"
# Pluggable and configurable code formatting platform written in Rust
brew "dprint"
# Embeddable SQL OLAP Database Management System
brew "duckdb"
# Utilities for the ext2, ext3, and ext4 file systems
brew "e2fsprogs"
# Utilities to read, write, and manipulate files in ext2/3/4 filesystems
brew "e2tools"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line tools for fly.io services
brew "flyctl"
# Fast and simple Node.js version manager
brew "fnm"
# Distributed software configuration management
brew "fossil"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Installer for the general purpose language Haskell
brew "ghcup"
# Distributed revision control system
brew "git"
# Automatic git commit --fixup
brew "git-absorb"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Cryptographic library based on the code from GnuPG
brew "libgcrypt"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Task is a task runner/build tool that aims to be simpler and easier to use
brew "go-task"
# Fast linters runner for Go
brew "golangci-lint"
# Database client and tools for the Go vulnerability database
brew "govulncheck"
# Like cURL, but for gRPC
brew "grpcurl"
# Kubernetes package manager
brew "helm"
# Cross-platform Java Version Manager
brew "jabba"
# Git-compatible distributed version control system
brew "jj"
# TUI for interacting with the Jujutsu version control system
brew "jjui"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Handy way to save and run project-specific commands
brew "just"
# Run local Kubernetes cluster in Docker
brew "kind"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Package manager for kubectl plugins
brew "krew"
# DNS library written in C
brew "ldns"
# Let's Encrypt client and ACME library
brew "lego"
# Language Server for the Lua language
brew "lua-language-server"
# Terminal-based visual file manager
brew "midnight-commander"
# C library for zip/unzip via zLib
brew "minizip"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# General purpose programming language in the ML family
brew "ocaml"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Extremely fast Python linter, written in Rust
brew "ruff"
# Rust toolchain installer
brew "rustup"
# Reimplementatilon of gpg and gpgv using Sequoia
brew "sequoia-chameleon-gnupg"
# Sequoia-PGP command-line tool
brew "sequoia-sq"
# Simple OpenPGP signature verification program
brew "sequoia-sqv"
# Editor of encrypted files
brew "sops"
# Thin wrapper for Terraform e.g. for locking state
brew "terragrunt"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Parser generator tool
brew "tree-sitter-cli"
# Simple terminal image viewer written in Rust
brew "viu"
# Pager/text based browser
brew "w3m"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Terminal Excel viewer with an interactive TUI
brew "xleak"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Fast static site generator in a single binary with everything built-in
brew "zola"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Generate images of code and terminal output.
brew "charmbracelet/tap/freeze", trusted: true
# Terraform
brew "hashicorp/tap/terraform"
# Terraform Language Server
brew "hashicorp/tap/terraform-ls"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Server and cloud storage browser
cask "cyberduck"
# Voice and text chat software
cask "discord"
cask "font-iosevka-term-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Homebrew's official GUI
cask "homebrew-app"
# Open-source screen recorder built with web technology
cask "kap"
# Password manager app
cask "keepassxc"
# Open-source keystroke visualiser
cask "keycastr"
# Electronics design automation suite
cask "kicad"
# App to manage software development and track bugs
cask "linear"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Android file transfer
cask "openmtp"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# A lightweight and high-performance screen recorder for macOS.
cask "lihaoyun6/tap/quickrecorder"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Menu bar customization tool
cask "swiftbar"
# AI image upscaler
cask "upscayl"
# Configurator of compatible keyboards in real time
cask "vial"
# REST, GraphQL and gRPC client
cask "yaak"
# Video communication and virtual meeting platform
cask "zoom"
go "github.com/go-delve/delve/cmd/dlv"
go "mvdan.cc/gofumpt"
go "golang.org/x/tools/gopls"
go "github.com/shurcooL/markdownfmt"
go "github.com/prometheus/promu"
go "honnef.co/go/tools/cmd/staticcheck"
go "github.com/hashicorp/terraform-ls"
go "terragrunt-ls"
go "github.com/mikefarah/yq/v4"
cargo "cargo-tarpaulin"
cargo "solo2"
cargo "ttyper"
krew "ctx"
krew "ice"
krew "krew"
krew "neat"
krew "ns"
krew "resource-capacity"
krew "stern"
krew "view-secret"
